package android.ext.content.image.params;

import android.content.Context;
import android.content.res.TypedArray;
import android.ext.util.DebugUtils;
import android.graphics.Bitmap.Config;
import android.graphics.BitmapFactory.Options;
import android.util.AttributeSet;

/**
 * Class <tt>PercentParameters</tt> is an implementation of a {@link Parameters}.
 * <h2>Usage</h2>
 * <p>Here is a xml resource example:</p><pre>
 * &lt;PercentParameters
 *      xmlns:app="http://schemas.android.com/apk/res-auto"
 *      app:config="[ argb_8888 | rgb_565 | alpha_8 ]"
 *      app:percent="0.7" /&gt;</pre>
 * @author Garfield
 */
public class PercentParameters extends Parameters {
    private static int[] PERCENT_PARAMETERS_ATTRS;
    private final int mTargetDensity;

    /**
     * Constructor
     * @param context The <tt>Context</tt>.
     * @param attrs The attributes of the XML tag that is inflating the data.
     * @see #PercentParameters(Context, Config, float)
     */
    public PercentParameters(Context context, AttributeSet attrs) {
        super(context, attrs);

        DebugUtils.__checkError(PERCENT_PARAMETERS_ATTRS == null, "The " + getClass().getName() + " did not call PercentParameters.initAttrs()");
        final TypedArray a = context.obtainStyledAttributes(attrs, PERCENT_PARAMETERS_ATTRS);
        value = a.getFloat(0 /* R.styleable.PercentParameters_percent */, 0);
        mTargetDensity = context.getResources().getDisplayMetrics().densityDpi;
        a.recycle();
    }

    /**
     * Constructor
     * @param context The <tt>Context</tt>.
     * @param config The {@link Config} to decode.
     * @param percent The percent to decode, expressed as a percentage of the image's size.
     * @see #PercentParameters(Context, AttributeSet)
     */
    public PercentParameters(Context context, Config config, float percent) {
        super(percent, config);
        mTargetDensity = context.getResources().getDisplayMetrics().densityDpi;
    }

    @Override
    public boolean requestDecodeBounds() {
        return true;
    }

    @Override
    public int computeByteCount(Context context, Options opts) {
        return computeByteCountImpl(context, opts);
    }

    @Override
    public void computeSampleSize(Context context, Options opts) {
        /*
         * Scale width, expressed as a percentage of the image's width.
         *      scale = opts.outWidth / (opts.outWidth * 0.7f); // scale 70%
         */
        opts.inSampleSize = 1;
        if ((float)value <= 0 || (float)value >= 1.0f) {
            opts.inDensity = opts.inTargetDensity = 0;
        } else {
            final float scale = opts.outWidth / (opts.outWidth * (float)value);
            opts.inTargetDensity = mTargetDensity;
            opts.inDensity = (int)(mTargetDensity * scale);
        }
    }

    /**
     * Initialize the {@link PercentParameters} styleable. <p>Note: This method recommended call in the
     * <tt>Application's</tt> static constructor.</p>
     * <p>Includes the following attributes:
     * <table><colgroup align="left" /><colgroup align="left" /><colgroup align="center" />
     * <tr><th>Attribute</th><th>Type</th><th>Index</th></tr>
     * <tr><td><tt>percent</tt></td><td>float</td><td>0</td></tr>
     * </table></p>
     * @param attrs The <tt>R.styleable.PercentParameters</tt> styleable, as generated by the aapt tool.
     */
    public static void initAttrs(int[] attrs) {
        PERCENT_PARAMETERS_ATTRS = attrs;
    }
}
